namespace NG.Velox.Context.Interfaces
{
    using NG.Velox.Interpretation.Data;
    using NG.Velox.Parsing.Data;
    using NG.Velox.Preprocessing.Data;

    /// <summary>
    /// Defines the execution context interface for the primary lexical and semantic interpretation phase of the pipeline.
    /// </summary>
    /// <remarks>
    /// Exposes unified access to the cumulative results of text processing phases alongside the property 
    /// for publishing hardware-ready execution state frames.
    /// </remarks>
    internal interface IInterpretationContext : IArenaContext
    {
        /// <summary>
        /// Gets the immutable results produced during the initial text preprocessing phase.
        /// </summary>
        /// <value>
        /// The <see cref="PreprocessingResult"/> structure containing structural metadata or block validation summaries.
        /// </value>
        PreprocessingResult PreprocessingResult { get; }

        /// <summary>
        /// Gets the immutable Abstract Syntax Tree (AST) components generated by the parser.
        /// </summary>
        /// <value>
        /// The <see cref="ParsingResult"/> structure containing the syntax tokens and numbers extracted from the stream.
        /// </value>
        ParsingResult ParsingResult { get; }

        /// <summary>
        /// Sets the interpretation container where hardware-ready state frames are recorded.
        /// </summary>
        /// <value>
        /// The <see cref="InterpretationResult"/> structural container used to store generated execution frames.
        /// </value>
        InterpretationResult InterpretationResult { set; }
    }
}
