using System.Runtime.CompilerServices;

namespace NG.Velox.Parsing.Core
{
    using NG.Velox.Lexing.Data;
    
    /// <summary>
    /// Provides a high-performance, zero-allocation sequential cursor over a tokenized lexical stream using raw unmanaged pointers.
    /// </summary>
    /// <remarks>
    /// This is a highly stateful, stack-only <see langword="ref struct"/> designed to act as the primary token consumption engine for the parser. 
    /// By maintaining raw unmanaged pointers directly to the token stream allocated within the <see cref="MemoryArena"/>, it completely 
    /// eliminates index-based bounds checking and managed heap overhead in hot parsing loops.
    /// <para/>
    /// It provides low-level streaming primitives such as lookahead validation (<see cref="Peek"/>), conditional consumption (<see cref="Match"/>), 
    /// and sequential advancement (<see cref="ReadToken"/>) optimized for maximum JIT inlining throughput.
    /// </remarks>
    internal unsafe ref struct TokenReader
    {
        private readonly Token* _tokensStart;
        private Token* _pCurrent;
        private readonly Token* _pEnd;

        /// <summary>
        /// Initializes a new instance of the <see cref="TokenReader"/> structure bound to the specified lexical result snapshot.
        /// </summary>
        /// <param name="lexingResult">The immutable token stream snapshot generated by the preceding lexical analysis phase.</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public TokenReader(in LexingResult lexingResult)
        {
            _tokensStart = lexingResult.Tokens;
            _pCurrent = lexingResult.Tokens;
            _pEnd = lexingResult.Tokens + lexingResult.Length;
        }

        /// <summary>
        /// Gets a value indicating whether the tracking cursor has reached the absolute boundary of the token stream.
        /// </summary>
        public readonly bool IsEof
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => _pCurrent >= _pEnd;
        }

        /// <summary>
        /// Gets the total number of tokens remaining available for consumption under the current cursor position.
        /// </summary>
        public readonly int Remaining
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => (int)(_pEnd - _pCurrent);
        }

        /// <summary>
        /// Gets the current absolute token element index relative to the origin of the lexical stream.
        /// </summary>
        public readonly int Position
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => (int)(_pCurrent - _tokensStart);
        }

        /// <summary>
        /// Returns a read-only reference to the token at the current cursor position without advancing the stream.
        /// </summary>
        /// <returns>A read-only reference to the current <see cref="Token"/>, or a default invalid token descriptor if the end of stream is reached.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly ref readonly Token Peek()
        {
            if (_pCurrent >= _pEnd) return ref Unsafe.NullRef<Token>();
            return ref *_pCurrent;
        }

        /// <summary>
        /// Returns a read-only reference to the token at a specific forward offset relative to the current cursor position without advancing the stream.
        /// </summary>
        /// <param name="offset">The forward lookahead offset index (e.g., <c>1</c> to peek at the next immediate token).</param>
        /// <returns>A read-only reference to the prospective <see cref="Token"/>, or a null reference if the lookahead exceeds stream boundaries.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly ref readonly Token Peek(int offset)
        {
            Token* target = _pCurrent + offset;
            if (target >= _pEnd || target < _tokensStart) return ref Unsafe.NullRef<Token>();
            return ref *target;
        }

        /// <summary>
        /// Consumes the current token and advances the unmanaged stream cursor by exactly one element.
        /// </summary>
        /// <returns>A direct copy or snapshot of the consumed <see cref="Token"/> structure before advancement.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Token ReadToken()
        {
            if (_pCurrent >= _pEnd) return default;

            Token token = *_pCurrent;
            _pCurrent++;
            return token;
        }

        /// <summary>
        /// Conditionally consumes the current token if its classification matches the expected kind, advancing the stream pointer.
        /// </summary>
        /// <param name="expectedKind">The targeting classification discriminator token group constraint.</param>
        /// <param name="token">When this method returns, contains the consumed token if the match succeeded; otherwise, a default empty structure.</param>
        /// <returns><see langword="true"/> if the current token matches the specified criteria and was consumed; otherwise, <see langword="false"/>.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public bool Match(TokenKind expectedKind, out Token token)
        {
            if (_pCurrent < _pEnd && _pCurrent->Kind == expectedKind)
            {
                token = *_pCurrent;
                _pCurrent++;
                return true;
            }

            token = default;
            return false;
        }

        /// <summary>
        /// Rewinds or fast-forwards the stream position cursor to an absolute index slot layout.
        /// </summary>
        /// <param name="position">The targeted absolute element index location within the bounds of the original token array.</param>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void Seek(int position)
        {
            Token* target = _tokensStart + position;
            if (target >= _tokensStart && target <= _pEnd)
            {
                _pCurrent = target;
            }
        }
    }
}
