namespace NG.Velox.Parsing.Interfaces
{
    using NG.Velox.Context.Interfaces;
    using NG.Velox.Diagnostic.Core;

    /// <summary>
    /// Defines the core contract for performance-critical syntactic parsers responsible for converting flat tokens into Abstract Syntax Tree (AST) nodes.
    /// </summary>
    /// <remarks>
    /// Implementations of this interface evaluate tokenized streams generated by the lexing layer along with 
    /// structural block meta-states to produce optimized, data-packed syntax sequences. The parsing phase 
    /// runs completely allocation-free on the managed heap to sustain high processing throughput.
    /// </remarks>
    internal interface IVeloxParser
    {
        /// <summary>
        /// Parses a tokenized lexical stream into structural Abstract Syntax Tree (AST) components 
        /// managed within the provided execution context.
        /// </summary>
        /// <typeparam name="TContext">The specific context type holding lexical tokens and state, constrained to zero-allocation structures.</typeparam>
        /// <param name="context">A reference to the mutable <typeparamref name="TContext"/> where new 16-byte explicit syntax nodes and structural results are recorded.</param>
        /// <param name="diagnosticBag">A reference to the localized compilation logger used to watch execution safety states and record grammatical anomalies.</param>
        /// <remarks>
        /// Enforces strict usage of ref modifiers across all structures combined with the anti-boxing 
        /// <see langword="allows ref struct"/> constraint. This guarantees zero-allocation execution characteristics, 
        /// preserves data locality, and eliminates value-type copying overhead inside hot syntax parsing paths.
        /// </remarks>
        void Process<TContext>(ref TContext context, ref DiagnosticBag diagnosticBag)
            where TContext : struct, IParsingContext, allows ref struct;
    }
}
