using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace NG.Velox.Helpers
{
    using NG.Velox.Memory.Core;

    /// <summary>
    /// Provides high-performance, type-safe static factory methods for allocating aligned unmanaged memory blocks from a <see cref="MemoryArena"/>.
    /// </summary>
    internal static unsafe class ArenaAllocator
    {
        /// <summary>
        /// Allocates a continuous unmanaged memory block sufficient to hold the specified number of sequential elements of type <typeparamref name="TEntity"/>, using proper alignment boundaries.
        /// </summary>
        /// <typeparam name="TEntity">The type of unmanaged elements to allocate memory for.</typeparam>
        /// <param name="arena">A mutable reference to the <see cref="MemoryArena"/> where the allocation is requested.</param>
        /// <param name="count">The total number of elements to reserve space for.</param>
        /// <returns>A raw typed pointer to the allocated block of memory, or <see langword="null"/> if <paramref name="count"/> is zero.</returns>
        /// <exception cref="OverflowException">Thrown if the total byte size calculation overflows maximum integer boundaries.</exception>
        /// <exception cref="OutOfMemoryException">Thrown when the arena does not have enough remaining capacity to satisfy the requested size and alignment alignment requirements.</exception>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static TEntity* Allocate<TEntity>(ref MemoryArena arena, int count)
            where TEntity : unmanaged
        {
            if (count == 0)
                return null;

            int size = checked(sizeof(TEntity) * count);
            int alignment = AlignOf<TEntity>();

            return (TEntity*)arena.Allocate(size, alignment);
        }

        /// <summary>
        /// Calculates the natural CPU alignment boundary requirements for the unmanaged type <typeparamref name="T"/> at runtime.
        /// </summary>
        /// <typeparam name="T">The unmanaged target type to check.</typeparam>
        /// <returns>The alignment boundary constraint in bytes (e.g., 1, 2, 4, or 8).</returns>
        /// <remarks>
        /// Computes alignment by wrapping the generic type inside a sequential structure next to a single byte field 
        /// and measuring the dynamic memory offset gap generated by the JIT compiler layout rules.
        /// </remarks>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private static int AlignOf<T>() where T : unmanaged
        {
            var layout = default(AlignmentHelper<T>);

            ref byte start = ref Unsafe.As<AlignmentHelper<T>, byte>(ref layout);
            ref byte field = ref Unsafe.As<T, byte>(ref layout.Value);

            return (int)Unsafe.ByteOffset(ref start, ref field);
        }

        /// <summary>
        /// An internal structure helper used strictly to calculate metadata for type alignment.
        /// </summary>
        /// <typeparam name="T">The unmanaged generic type under inspection.</typeparam>
        [StructLayout(LayoutKind.Sequential)]
        private struct AlignmentHelper<T> where T : unmanaged
        {
            /// <summary>
            /// A baseline byte field to force trailing alignment padding based on target type restrictions.
            /// </summary>
            public byte Target;

            /// <summary>
            /// The actual generic value field to measure the offset position against.
            /// </summary>
            public T Value;
        }
    }
}
