name: .NET CI & CD

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v[0-9]*'
      - '[0-9]*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'
        
    - name: Restore dependencies
      run: |
        dotnet restore src/NG.Velox/NG.Velox.csproj
        dotnet restore tests/NG.Velox.Tests/NG.Velox.Tests.csproj
        dotnet restore benchmarks/NG.Velox.Benchmarks/NG.Velox.Benchmarks.csproj
      
    - name: Build
      run: dotnet build src/NG.Velox/NG.Velox.csproj --no-restore -c Release
      
    - name: Test
      run: dotnet test tests/NG.Velox.Tests/NG.Velox.Tests.csproj --no-restore -c Release

  publish-nuget:
    needs: build-and-test
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Pre-update Version in README files
      id: update-readme
      run: |
        RAW_TAG=${{ github.ref_name }}
        CLEAN_VERSION=$(echo "$RAW_TAG" | sed 's/^v//')
        
        sed -i "s/\(# \(MachineGate\.\)\?NG\.Velox v\)[0-9]*\.[0-9]*\.[0-9]*\([-a-zA-Z0-9.]*\)*/\1$CLEAN_VERSION/g" README.md
        sed -i "s/\(dotnet add package MachineGate.NG.Velox --version \)[0-9]*\.[0-9]*\.[0-9]*\([-a-zA-Z0-9.]*\)*/\1$CLEAN_VERSION/g" README.md
        
        sed -i "s/\(# \(MachineGate\.\)\?NG\.Velox v\)[0-9]*\.[0-9]*\.[0-9]*\([-a-zA-Z0-9.]*\)*/\1$CLEAN_VERSION/g" README.NuGet.md
        sed -i "s/\(dotnet add package MachineGate.NG.Velox --version \)[0-9]*\.[0-9]*\.[0-9]*\([-a-zA-Z0-9.]*\)*/\1$CLEAN_VERSION/g" README.NuGet.md

    - name: NuGet Login
      uses: NuGet/login@v1
      id: nuget-login
      with:
        user: MachineGate

    - name: Pack library
      run: |
        RAW_TAG=${{ github.ref_name }}
        CLEAN_VERSION=$(echo "$RAW_TAG" | sed 's/^v//')
        
        dotnet pack src/NG.Velox/NG.Velox.csproj -c Release \
          /p:PackageId=MachineGate.NG.Velox \
          /p:PackageVersion=$CLEAN_VERSION \
          /p:PackageReleaseNotes="Automated release for version $CLEAN_VERSION" \
          /p:DeterministicSourcePaths=true

    - name: Push to NuGet
      run: |
        dotnet nuget push src/NG.Velox/bin/Release/*.nupkg \
          --api-key "${{ steps.nuget-login.outputs.NUGET_API_KEY }}" \
          --source https://nuget.org \
          --skip-duplicate

    - name: Commit and Push README to GitHub
      run: |
        RAW_TAG=${{ github.ref_name }}
        CLEAN_VERSION=$(echo "$RAW_TAG" | sed 's/^v//')
        
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@://github.com"
        
        git add README.md README.NuGet.md
        git diff-index --quiet HEAD || (git commit -m "chore: update README versions to $CLEAN_VERSION [skip ci]" && git push origin HEAD:main)
